ofdispatcher/dispatcher/urls.py
from django.conf.urls import patterns, url

from dispatcher import views

urlpatterns = patterns('',
                       url(r'^$', views.overview, name='overview'),
                       url(r'^alarms/$', views.alarms, name='alarms'),
                       url(r'^department/$', views.department, name='department'),
                       url(r'^loops/$', views.loops, name='loops'),
                       url(r'^contacts/$', views.contacts, name='contacts'),
                       url(r'^contacts/create/$', views.contact_create, name='contacts_create'),
                       url(r'^contacts/(?P<id>\d+)/update/$', views.contact_update, name='contacts_update'),
                       url(r'^contacts/(?P<id>\d+)/delete/$', views.contact_delete, name='contacts_delete'),
                       )

ofdispatcher/ofdispatcher/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = patterns('',
   url(r'^$', RedirectView.as_view(url='/dispatcher/', permanent=True)),
   url(r'^dispatcher/', include('dispatcher.urls', namespace='dispatcher')),
   url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
   url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', name='logout'),
   url(r'^admin/', include(admin.site.urls)),
)

ofdispatcher/dispatcher/models.py
import logging
from django.db import models
from datetime import datetime
from django.conf import settings
from django.contrib.auth.models import User

logger = logging.getLogger(__name__)


class Department(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=128)
    name2 = models.CharField(max_length=128, blank=True)
    sms_gateway_driver = models.IntegerField(default=0)
    sms_gateway_sender = models.IntegerField(default=112112112)
    sms_gateway_api_key = models.CharField(max_length=256, blank=True)
    comment = models.TextField(blank=True)  # hidden comment
    news = models.TextField(blank=True)  # public notification

    def __unicode__(self):
        return self.name


class DepartmentManager(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.OneToOneField(User)
    department = models.ForeignKey(Department)

    def __unicode__(self):
        return '%s-%s' % (str(self.user), str(self.department))


class Contact(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    department = models.ForeignKey(Department)
    firstname = models.CharField(max_length=128)
    secondname = models.CharField(max_length=128)
    mail1 = models.EmailField(blank=True)
    mail2 = models.EmailField(blank=True)
    sms1 = models.IntegerField(default=0)
    sms2 = models.IntegerField(default=0)
    test = models.BooleanField(default=True)
    error = models.BooleanField(default=False)
    dev = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return '%s, %s' % (self.secondname, self.firstname)

    def update_alarmloop_assignment(self, loops):
        '''
        Add this user to all AlarmLoops which are specified
        in the loops list. The list has to contain
        AlarmLoop ids.
        '''
        # remove this contact from all loops
        for al in AlarmLoop.objects.all():
            al.contacts.remove(self)
        # re-assign contact to loop(s) specified in list
        loop_list = []
        for loop_id in loops:
            al = AlarmLoop.objects.get(id=int(loop_id))
            loop_list.append(al)
            al.contacts.add(self)
        logger.info('Contact %s assigned to loops: %s', self, loop_list)
        return loop_list

    def get_alarmloop_assignment(self):
        '''
        Returns list of AlarmLoops that to which this contact
        is currently assigned.
        '''
        return [l for l in AlarmLoop.objects.filter(contacts=self)]


class AlarmLoop(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    department = models.ForeignKey(Department)
    contacts = models.ManyToManyField(Contact, blank=True)
    loop = models.CharField(max_length=5, default='00000')
    name = models.CharField(max_length=128, default='Schleife')
    alarm_text = models.CharField(max_length=140,
                                  default='Feuerwehr Alarmierung!')
    alarm_text_long = models.TextField(blank=True)
    active = models.BooleanField(default=True)
    # definition of test alarm times for this loop
    test_alarm_day = models.IntegerField(default=5)  # Mo=0,...
    test_alarm_date_min = models.IntegerField(default=1)  # e.g. 1
    test_alarm_date_max = models.IntegerField(default=7)  # e.g. 7
    test_alarm_hour = models.IntegerField(default=12)  # start hour
    test_alarm_minute = models.IntegerField(default=10)  # start minute
    test_alarm_period = models.IntegerField(default=30)  # test period

    def __unicode__(self):
        return self.loop


class Alarm(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    loop = models.ForeignKey(AlarmLoop)
    message = models.TextField(blank=False)
    log = models.TextField(blank=True)
    type = models.IntegerField(default=0)
    comment = models.TextField(blank=True)

    def __unicode__(self):
        return 'Alarm (%s)' % str(self.created)

ofdispatcher/dispatcher/forms.py
from django import forms
from dispatcher.models import Contact, AlarmLoop


class ContactForm(forms.ModelForm):

    loops_choices = []
    loops = forms.MultipleChoiceField(
        required=True,
        label='Schleifen',
        help_text='Schleifen bei denen diese Einsatzkraft alarmiert werden soll (STRG fuer Mehrfachauswahl).',
        choices=loops_choices)

    class Meta:
        model = Contact
        fields = (
            'firstname',
            'secondname',
            'mail1',
            'sms1',
            'active',
            'test'
        )

        labels = {
            'firstname': 'Vorname',
            'secondname': 'Nachname',
            'mail1': 'E-Mail Adresse',
            'sms1': 'Handynummer',
            'active': 'Aktiviert',
            'test': 'Testalarmierungen',
        }

        help_texts = {
            'mail1': 'Die E-Mail Adresse an die der Alarm versendet wird.',
            'sms1': 'Die Handynummer an die der Alarm versendet wird.',
            'active': 'Alarmierungen werden nur an als "Aktiviert" markierte Einsatzkraefte versendet',
            'test': 'Die monatliche Testalarmierungen an diese Einsatzkraft versenden.',
        }

    def update_loop_choices(self, department, contact=None):
        # get loops that are valid for a contact and add them to form
        self.fields['loops'].choices = [
            (l.id, l.loop) for l in AlarmLoop.objects.filter(
                department=department)]
        # set pre selected items for contact
        if contact is not None:
            selected = [
                l.id for l in contact.get_alarmloop_assignment()]
            self.fields['loops'].initial = selected

ofdispatcher/dispatcher/views.py
import logging
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib import messages
from dispatcher.models import AlarmLoop, Contact
from dispatcher.forms import ContactForm


logger = logging.getLogger(__name__)


@login_required
def overview(request):
    return render(request, 'dispatcher/overview.html', None)


@login_required
def alarms(request):
    return render(request, 'dispatcher/alarms.html', None)


@login_required
def department(request):
    return render(request, 'dispatcher/department.html', None)


@login_required
def loops(request):
    department = request.user.departmentmanager.department
    alarm_loop_list = AlarmLoop.objects.filter(department=department)
    context = {'alarm_loops': alarm_loop_list}
    return render(request, 'dispatcher/loops.html', context)


@login_required
def contacts(request):
    department = request.user.departmentmanager.department
    contact_list = Contact.objects.filter(department=department)
    # add loops to returned contacts
    for c in contact_list:
        c.loops = AlarmLoop.objects.filter(contacts=c)
    # return list and render view
    context = {'contacts': contact_list}
    return render(request, 'dispatcher/contacts.html', context)


@login_required
def contact_create(request):
    # get department of user
    department = request.user.departmentmanager.department

    if request.method == 'POST':
        # POST request: process data
        # create form instance an add received data
        form = ContactForm(request.POST)
        form.update_loop_choices(department)
        # check data and process it
        if form.is_valid():
            # create new contact
            c = form.save(commit=False)
            c.department = department
            c.save()
            logger.info('%s created contact: %s', request.user, c)
            c.update_alarmloop_assignment(form.cleaned_data['loops'])
            # redirect to list view
            return redirect('dispatcher:contacts')
    else:
        # GET request: return empty form
        form = ContactForm()
        form.update_loop_choices(department)
    context = {'form': form}
    return render(request, 'dispatcher/contact_create.html', context)


@login_required
def contact_update(request, id):
    # get department of user to ensure that he is allowed to access contact
    department = request.user.departmentmanager.department
    # get Contact from model that should be updated
    c = get_object_or_404(Contact, id=id, department=department)

    if request.method == 'POST':
        # POST request: process data
        # create form instance an add received data
        form = ContactForm(request.POST, instance=c)
        form.update_loop_choices(department)
        # check data and process it
        if form.is_valid():
            form.save()
            logger.info('%s updated contact: %s', request.user, c)
            c.update_alarmloop_assignment(form.cleaned_data['loops'])
            # redirect to list view
            return redirect('dispatcher:contacts')
    else:
        # GET request: return initial form
        form = ContactForm(instance=c)
        form.update_loop_choices(department, c)
    context = {'contact': c, 'form': form}
    return render(request, 'dispatcher/contact_update.html', context)


@login_required
def contact_delete(request, id):
    # get department of user to ensure that he is allowed to access contact
    department = request.user.departmentmanager.department
    # get Contact from model that should be updated
    c = get_object_or_404(Contact, id=id, department=department)

    if request.method == 'POST':
        # perform action for dialog result
        if 'ok' in request.POST:
            # delete contact
            c.delete()
            logger.info('%s deleted contact: %s', request.user, c)
        # redirect to list view
        return redirect('dispatcher:contacts')
    else:
        # show confirmation dialog
        action = reverse('dispatcher:contacts_delete', kwargs={'id': c.id})
        message = 'Einsatzkraft: %s %s loeschen?' % (c.firstname, c.secondname)
        buttons = {'ok': 'Ja', 'cancel': 'Nein'}
        context = {'action': action, 'message': message, 'buttons': buttons}
        return render(request, 'dispatcher/generic_yes_no.html', context)

ofdispatcher/dispatcher/templates/dispatcher/alarms.html
{% extends "dispatcher/base.html" %}

{% block title %}Alarmierungen{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-7">
		
		<div class="row sub-content">
		</div>
		<div class="row sub-content">
			<table  class="table table-striped">
				<tr>
					<th>Datum</th>
					<th>Schleife</th>
					<th>Text</th>
				</tr>
				<tr>
					<td>10.11.14 16:34</td>
					<td><code>51372</code></td>
					<td>Feuerwehr Einsatz. Schleife 51234. (10.11.14 16:34)</td>
				</tr>
					
			</table>
		</div>
	
	</div>
</div>
{% endblock %}

ofdispatcher/dispatcher/templates/dispatcher/base.html
<!DOCTYPE html>
<html>
<head>
	<title>OpenFire Cloud</title>
	
	{% load staticfiles %}
	<!-- Bootstrap -->
	<link rel="stylesheet" type="text/css" href="{% static 'dispatcher/bootstrap/css/bootstrap.min.css' %}" />
	<!-- custom css -->
	<link rel="stylesheet" type="text/css" href="{% static 'dispatcher/css/main.css' %}" />

	<!-- jQuery -->
	<script  type="text/javascript" src="{% static 'dispatcher/jquery/jquery-1.11.1.js' %}"></script>
	<!-- Bootstrap -->
	<script  type="text/javascript" src="{% static 'dispatcher/bootstrap/js/bootstrap.min.js' %}"></script>
	<script  type="text/javascript" src="{% static 'dispatcher/bootstrap/js/bootbox.min.js' %}"></script>
</head>

<body>
	<div id="main-div">
	{% block body %}		
	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">OpenFire Cloud</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">		

					<li><a href="{% url 'dispatcher:overview' %}">Übersicht</a></li>
					<!--<li><a href="{% url 'dispatcher:department' %}">Feuerwehr</a></li>-->
					<li><a href="{% url 'dispatcher:loops' %}">Schleifen</a></li>
					<li><a href="{% url 'dispatcher:contacts' %}">Einsatzkräfte</a></li>
					<li><a href="{% url 'dispatcher:alarms' %}">Alarmierungen</a></li>
					<!--
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Select UE <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu" id="ue_dropdown_list">
							<li>Not connected</li>
							<li><a href="#">UE PB 1</a></li>
							<li><a href="#">UE PB 2</a></li>
						</ul>
					</li>
				-->	
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<a type="button" class="btn btn-danger disabled" href="#">Alarmieren</a>
				<a type="button" class="btn btn-primary navbar-btn" href="{% url 'django.contrib.auth.views.logout' %}">Abmelden &nbsp;<span class="glyphicon glyphicon-off"></a>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>


<div class="row">
	<!--
	<div class="col-md-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Menü</h3>
			</div>
  			<div class="panel-body">
				{% block sidebar %}
				{% endblock %}
			</div>
		</div>
	</div>
	-->
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">{% block title %}{% endblock %}</h3>
			</div>
			<div class="panel-body">
				{% block content %}Content{% endblock %}
			</div>
		</div>
	</div>
	
</div>

{% endblock %}

<footer class="footer text-center"> <small>Version: 0.1 (beta)</small><br><span class="glyphicon glyphicon-copyright-mark"></span> 2014 by Manuel Peuster (<a href="mailto:openfire@peuster.de">openfire@peuster.de</a>)</footer>
</div>
</body>
</html>

ofdispatcher/dispatcher/templates/dispatcher/contact_create.html
{% extends "dispatcher/base.html" %}
{% load bootstrap3 %}

{% block title %}Einsatzkraft anlegen{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-7">
		
		<form action="{% url 'dispatcher:contacts_create' %}" method="post">
			{% csrf_token %}
			{% bootstrap_form form %}
			{% buttons %}
			<button type="submit" class="btn btn-primary">
				{% bootstrap_icon "plus-sign" %} Einsatzkraft anlegen
			</button>
			<a type="button" class="btn btn-default" href="{% url 'dispatcher:contacts' %}">
				Anlegen abbrechen
			</a>
			{% endbuttons %}
		</form>
	
	</div>
</div>
{% endblock %}

ofdispatcher/dispatcher/templates/dispatcher/contact_update.html
{% extends "dispatcher/base.html" %}
{% load bootstrap3 %}

{% block title %}Einsatzkraft bearbeiten{% endblock %}


{% block content %}
<div class="row">
	<div class="col-md-7">
		{% for message in messages %}
    		<div class="alert alert-{{ message.tags }}">{{ message }}</div>
		{% endfor %}
		
		<form action="{% url 'dispatcher:contacts_update' contact.id %}" method="post">
			{% csrf_token %}
			{% bootstrap_form form %}

			<p><small>Erstellt am {{ contact.created|date:"d.m.Y" }} um {{ contact.created|date:"H:i:s" }} Uhr</small></p>
			<p><small>Geändert am {{ contact.updated|date:"d.m.Y" }} um {{ contact.updated|date:"H:i:s" }} Uhr</small></p>

			{% buttons %}
			<button type="submit" class="btn btn-primary">
				{% bootstrap_icon "plus-sign" %} Änderungen speichern
			</button>
			<a type="button" class="btn btn-default" href="{% url 'dispatcher:contacts' %}">
				Änderungen verwerfen
			</a>
			<a type="button" class="btn btn-danger" href="{% url 'dispatcher:contacts_delete' contact.id %}">
				{% bootstrap_icon "trash" %} Einsatzkraft löschen
			</a>
			{% endbuttons %}
		</form>
	
	</div>
</div>
{% endblock %}

ofdispatcher/dispatcher/templates/dispatcher/contacts.html
{% extends "dispatcher/base.html" %}

{% block title %}Einsatzkräfte{% endblock %}


{% block content %}
<div>
	<div>
		<div class="row sub-content">
			<a type="button" class="btn btn-primary pull-right" href="{% url 'dispatcher:contacts_create' %}">Neue Einsatzkraft anlegen &nbsp;<span class="glyphicon glyphicon-plus-sign"></a>
			<br><br>
		</div>
		<div class="row sub-content">
			<table class="table table-striped">
				<tr>
					<th>Name</th>
					<th>Gändert</th>
					<th>Schleife(n)</th>
					<th class="text-center">Status</th>
					<th>
					</th>
				</tr>
				{% for contact in contacts %}
				<tr>
					<td>{{ contact.secondname }}, {{ contact.firstname }}</td>
					<td>{{ contact.updated|date:"d.m.Y H:i" }}</td>
					<td>
					{% for loop in contact.loops %}
						<code>{{ loop.loop }}</code>  
					{% endfor %}
					</td>
					<td class="text-center">
						{% if contact.active %}
						<span class="label label-success">Aktiv</span>
						{% else %}
						<span class="label label-danger">Inaktiv</span>
						{% endif %}
					</td>
					<td align="right">
						<a type="button" class="btn btn-xs btn-default" href="{% url 'dispatcher:contacts_update' contact.id %}">Bearbeiten &nbsp;<span class="glyphicon glyphicon-edit"></a>
						<a type="button" class="btn btn-xs btn-default" href="{% url 'dispatcher:contacts_delete' contact.id %}">Entfernen &nbsp;<span class="glyphicon glyphicon-trash"></a>
					</td>
				</tr>
				{% endfor %}
			</table>
		</div>
	</div>
</div>
{% endblock %}

ofdispatcher/dispatcher/templates/dispatcher/contacts_update.html
{% extends "dispatcher/base.html" %}

{% block title %}Einsatzkraft bearbeiten{% endblock %}


{% block content %}
<div class="row">
	<div class="col-md-7">
		
		Contact Detail
	
	</div>
</div>
{% endblock %}

ofdispatcher/dispatcher/templates/dispatcher/department.html
{% extends "dispatcher/base.html" %}

{% block title %}Feuerwehr{% endblock %}

{% block sidebar %}
<ul class="nav nav-stacked">
	<li><a href="#">Feuerwehr</a></li>
</ul>
{% endblock %}

{% block content %}
<h3>FF Nieder-Werbe<br>
<small>Stadt Waldeck</small></h3>

<div class="row">
<div class="col-md-6">
<form role="form">
  <div class="form-group">
    <label for="sms_from">SMS Absender</label>
    <input type="text" class="form-control" id="sms_from" placeholder="Nummer">
  </div>
  <div class="form-group">
    <label for="sms_token">SMS Gateway Token</label>
    <input type="text" class="form-control" id="sms_token" placeholder="Token">
    <p>Zugangsschlüssel für SMS Gateway. Bitte genau prüfen. Sollte der Schlüssel falsch sein, werden keine SMS versendet.</p>
  </div>
  <button type="submit" class="btn btn-success">Speichern</button>
</form>
</div>
</div>

{% endblock %}

ofdispatcher/dispatcher/templates/dispatcher/generic_yes_no.html
{% extends "dispatcher/base.html" %}
{% load bootstrap3 %}

{% block title %}{{ message }}{% endblock %}


{% block content %}
<div class="row">
	<div class="text-center">
		<form action="{{ action }}" method="post">
			{% csrf_token %}
			{% buttons %}
			<button type="submit" class="btn btn-primary" name="ok">{% bootstrap_icon "ok" %} {{ buttons.ok }}</button> 
			<button type="submit" class="btn btn-primary" name ="cancel">{% bootstrap_icon "remove" %} {{ buttons.cancel }}</button> 
			{% endbuttons %}
		</form>
	
	</div>
</div>
{% endblock %}

ofdispatcher/dispatcher/templates/dispatcher/home.html
{% extends "dispatcher/base.html" %}

{% block title %} - Login{% endblock %}

{% block content %}
Das ist der Inhalt.
{% endblock %}

ofdispatcher/dispatcher/templates/dispatcher/loops.html
{% extends "dispatcher/base.html" %}

{% block title %}Schleifen{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-7">
		{% for loop in alarm_loops %}
		<h4 class="text-muted text-uppercase conent_headline">{{ loop.loop }}
		{% if loop.active %}
		<span class="label label-success pull-right">Aktiv</span>
		{% else %}
		<span class="label label-danger pull-right">Inaktiv</span>
		{% endif %}
		</h4>
		<div class="sub-content">

				<div class="form-group">
					<label for="sms_from">Name</label>
					<input type="text" class="form-control" placeholder="Name" value="{{ loop.name }}" disabled>
				</div>
				<div class="form-group">
					<label for="sms_from">Alarm Text</label>
					<input type="text" class="form-control" placeholder="Name" value="{{ loop.alarm_text }}" disabled>
				</div>
				<a type="button" class="btn btn-sm btn-primary" href="bla?id={{ loop.id }}">Bearbeiten</a>
				<a type="button" class="btn btn-sm btn-primary disabled" href="#">Einsatzkräfte</a>
				<a type="button" class="btn btn-sm btn-danger disabled" href="#">Alarmieren</a>

		</div>
		<hr>
		{% endfor %}
	</div>
</div>
{% endblock %}

ofdispatcher/dispatcher/templates/dispatcher/overview.html
{% extends "dispatcher/base.html" %}

{% block title %}Übersicht{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-7">

		<h4 class="text-muted text-uppercase conent_headline">Feuerwehr</h4>
		<div class="sub-content">
			<h3>FF Nieder-Werbe<br>
			<small>Stadt Waldeck</small></h3>
			<p>Schleifen: <strong>2</strong></p>
			<p>Einsatzkräfte: <strong>31</strong></p>
		</div>
		<hr>
		<h4 class="text-muted text-uppercase conent_headline">Administratoren</h4>
		<div class="sub-content">
			Heinz Mustermann <a href="">(musterman@mail.de)</a><br>
			Heinz Mustermann <a href="">(musterman@mail.de)</a><br>
			Heinz Mustermann <a href="">(musterman@mail.de)</a><br>
		</div>
		<hr>
		<h4 class="text-muted text-uppercase conent_headline">News</h4>
		<div class="sub-content">
			Keine News vorhanden.
		</div>
		<hr>
		<h4 class="text-muted text-uppercase conent_headline">Kontakt</h4>
		<div class="sub-content">
			Bei möglichen Fehlern oder sonstigen Fragen, bitte per E-Mail an <a href="mailto:openfire@peuster.de">openfire@peuster.de</a> wenden. Die SMS Alarmierung ersetzt keineswegs die offizielle Alarmierung per FME oder Sirene. Fehlarlarme sind nicht ausgeschlossen.
		</div>
		<hr>
		</div>
		<div class="col-md-1"></div>
		<div class="col-md-4">
			<h4 class="text-muted text-uppercase conent_headline">Letzte Alarmierungen</h4>
				<table class="table table-striped">
					<tr>
						<td>10.11.14 16:34</td>
						<td><code>51372</code></td>
						<td><a href=""><span class="glyphicon glyphicon-search"></span></a></td>
					</tr>
					<tr>
						<td>09.11.14 04:33</td>
						<td><code>51372</code></td>
						<td><a href=""><span class="glyphicon glyphicon-search"></span></a></td>
					</tr>
					<tr>
						<td>01.07.14 11:34</td>
						<td><code>51399</code></td>
						<td><a href=""><span class="glyphicon glyphicon-search"></span></a></td>
					</tr>
					<tr>
						<td>10.05.14 13:34</td>
						<td><code>51372</code></td>
						<td><a href=""><span class="glyphicon glyphicon-search"></span></a></td>
					</tr>
				</table>
		</div>
	</div>
	{% endblock %}